package executor_test

import (
	"bytes"
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/illinoisdata/readie/worker/internal/executor"
	"github.com/illinoisdata/readie/worker/internal/logging"
)

// The wire format is implemented twice, here and in Python, and two hand-written
// implementations of one format drift. This fixture is generated by
// executor/tests/generate_golden.py and decoded by both suites, so a change to
// either side that the other does not follow fails a test rather than a restore
// six weeks later.
//
// Regenerate with: cd executor && uv run python tests/generate_golden.py

const goldenPath = "../../../executor/tests/data/frames.golden.json"

type goldenFile struct {
	ProtocolVersion int `json:"protocol_version"`
	Cases           []struct {
		Name       string `json:"name"`
		PayloadHex string `json:"payload_hex"`
		EncodedHex string `json:"encoded_hex"`
	} `json:"cases"`
}

func loadGolden(t *testing.T) goldenFile {
	t.Helper()

	raw, err := os.ReadFile(filepath.Clean(goldenPath))
	require.NoError(t, err, "the fixture is generated by executor/tests/generate_golden.py")

	var golden goldenFile
	require.NoError(t, json.Unmarshal(raw, &golden))
	require.NotEmpty(t, golden.Cases)
	return golden
}

func decodeHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	require.NoError(t, err)
	return b
}

func TestGolden_MatchesThisProtocolVersion(t *testing.T) {
	// A version bump without regenerating the fixture leaves both suites
	// validating the format nobody speaks any more.
	assert.Equal(t, executor.ProtocolVersion, loadGolden(t).ProtocolVersion)
}

// Decoding the fixture with this package's reader is the actual agreement
// check: these bytes were produced by the Python side's understanding of the
// format.
func TestGolden_PythonEncodingDecodesHere(t *testing.T) {
	for _, tc := range loadGolden(t).Cases {
		t.Run(tc.Name, func(t *testing.T) {
			encoded := decodeHex(t, tc.EncodedHex)
			want := decodeHex(t, tc.PayloadHex)

			client, server := net.Pipe()
			t.Cleanup(func() { _ = client.Close(); _ = server.Close() })

			go func() {
				_, _ = server.Write(encoded)
				_ = server.Close()
			}()

			session := executor.NewSession(client, executor.SessionOptions{
				ChunkSize:        7, // deliberately awkward: forces multi-read chunks
				FirstByteTimeout: 5 * time.Second,
				IdleTimeout:      5 * time.Second,
			}, logging.Discard())

			var got bytes.Buffer
			require.NoError(t, session.ReadResponse(context.Background(), func(p []byte) error {
				got.Write(p)
				return nil
			}))
			// bytes.Equal rather than assert.Equal: an empty payload is nil
			// on one side and []byte{} on the other, and both mean no bytes.
			assert.True(t, bytes.Equal(want, got.Bytes()),
				"want %x, got %x", want, got.Bytes())
		})
	}
}

// The reverse direction: what this package writes must decode to the same
// payload the fixture names. Not byte-equality with the fixture -- chunk
// boundaries are a sender's choice -- but the payload has to survive.
func TestGolden_ThisEncodingDecodesToTheSamePayload(t *testing.T) {
	for _, tc := range loadGolden(t).Cases {
		t.Run(tc.Name, func(t *testing.T) {
			payload := decodeHex(t, tc.PayloadHex)

			client, server := net.Pipe()
			t.Cleanup(func() { _ = client.Close(); _ = server.Close() })

			received := make(chan []byte, 1)
			go func() {
				body, err := readFramedMessage(server)
				if err != nil && !errors.Is(err, io.EOF) {
					received <- nil
					return
				}
				received <- body
			}()

			session := executor.NewSession(client, executor.SessionOptions{
				ChunkSize:    16,
				WriteTimeout: 5 * time.Second,
			}, logging.Discard())

			for offset := 0; offset < len(payload); offset += 16 {
				end := min(offset+16, len(payload))
				require.NoError(t, session.WriteChunk(payload[offset:end]))
			}
			require.NoError(t, session.CloseRequest())

			select {
			case got := <-received:
				assert.True(t, bytes.Equal(payload, got), "want %x, got %x", payload, got)
			case <-time.After(5 * time.Second):
				t.Fatal("the framed message never completed")
			}
		})
	}
}
