syntax = "proto3";

option go_package = "github.com/illinoisdata/checkpoint-restore-for-serverless/worker/proto";

// Message used for code execution requests to workers
message WorkerExecutionRequest {
  string          container_id         = 1;
  bytes           payload              = 2;
  optional int64  cpu_alloc            = 3;
  optional int64  gpu_alloc            = 4;
  repeated string required_resources   = 5;
  repeated string additional_resources = 6;
}

// Message used for code execution responses from workers
message WorkerExecutionResponse {
  string container_id = 1;
  bool   success      = 2;
  string stdout       = 3;
  string stderr       = 4;
}

// Message used for executor provisioning requests to workers
message ExecutorProvisionRequest {
  string          checkpoint_id = 1;
  optional string container_id  = 2;
  int64           cpu_alloc     = 3;
  int64           gpu_alloc     = 4;
}

// Message used for executor provisioning responses from workers
message ExecutorProvisionResponse {
  string container_id = 1;
  int64  cpu_alloc    = 2;
  int64  gpu_alloc    = 3;
}

// Service on the worker nodes to handle execution requests
service ExecutionService {
  // Unary RPC for requesting provisioning of a new executor or restarting an executor on worker
  rpc RequestProvision(ExecutorProvisionRequest) returns (ExecutorProvisionResponse);

  // Bi-directional streaming RPC for streaming code execution input and output
  rpc RequestExecution(stream WorkerExecutionRequest) returns (stream WorkerExecutionResponse);
}