syntax = "proto3";

option go_package = "github.com/illinoisdata/checkpoint-restore-for-serverless/worker/proto";

enum Status {
  STATUS_UNKNOWN = 0;
  STATUS_READY   = 2;
  STATUS_BUSY    = 3;
  STATUS_ERROR   = 4;
  STATUS_REMOVED = 5;
}

// Message used for posting worker status
message WorkerStatus {
  string worker_id  = 1;
  string worker_uri = 2;
  Status status     = 3;
}

// Message used for posting executor status
message ExecutorStatus {
  string container_id = 1;
  string worker_id    = 2;
  string request_id   = 3;
  string session_id   = 4;
  Status status       = 5;
}

// Message used for posting worker utilization
message WorkerUtilization {
  string worker_id = 1;
  int64  cpu_util  = 2;
  int64  cpu_total = 3;
  int64  gpu_util  = 4;
  int64  gpu_total = 5;
}

// Message used for posting executor utilization
message ExecutorUtilization {
  string container_id = 1;
  string worker_id    = 2;
  int64  cpu_util     = 3;
  int64  cpu_total    = 4;
  int64  gpu_util     = 5;
  int64  gpu_total    = 6;
}

message RegistryUpdateResponse {
  bool updated = 1;
}

// Service on the main node to handle status and utilization updates from workers and executors
service RegistryService {
  // Unary RPC for posting worker status
  rpc PostWorkerStatus(WorkerStatus) returns (RegistryUpdateResponse);

  // Unary RPC for posting executor status
  rpc PostExecutorStatus(ExecutorStatus) returns (RegistryUpdateResponse);

  // Unary RPC for posting worker utilization
  rpc PostWorkerUtilization(WorkerUtilization) returns (RegistryUpdateResponse);

  // Unary RPC for posting executor utilization
  rpc PostExecutorUtilization(ExecutorUtilization) returns (RegistryUpdateResponse);
}