syntax = "proto3";

option go_package = "github.com/illinoisdata/checkpoint-restore-for-serverless/worker/proto";

// Message used for worker status
message WorkerStatus {
  string worker_id = 1;
  string status    = 2;
}

// Message used for executor status
message ExecutorStatus {
  string container_id = 1;
  string worker_id    = 2;
  string status       = 3;
}

service RegistryService {
  rpc PostWorkerStatus(WorkerStatus) returns (WorkerStatus);

  rpc PostExecutorStatus(ExecutorStatus) returns (ExecutorStatus);
}