syntax = "proto3";

// Message used for code execution requests from clients
message ClientExecutionRequest {
  string request_id = 1;
  bytes  payload    = 2;
}

// Message used for code execution responses to clients
message ClientExecutionResponse {
  string stdout = 1;
  string stderr = 2;
}

// Message used for code execution requests to workers
message WorkerExecutionRequest {
  string request_id   = 1;
  bytes  payload      = 2;
  string worker_id    = 3;
  string container_id = 4;
}

// Message used for code execution responses from workers
message WorkerExecutionResponse {
  string request_id = 1;
  string stdout     = 2;
  string stderr     = 3;
}

service RouterService {
  rpc RequestExecution(stream ClientExecutionRequest) returns (stream ClientExecutionResponse);

  rpc AssignExecution(stream WorkerExecutionRequest) returns (stream WorkerExecutionResponse);
}