# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crfs_router.proto import registry_pb2 as crfs__router_dot_proto_dot_registry__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crfs_router/proto/registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryServiceStub:
    """Service on the router to handle status and utilization updates from workers and executors
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostWorkerStatus = channel.unary_unary(
                '/RegistryService/PostWorkerStatus',
                request_serializer=crfs__router_dot_proto_dot_registry__pb2.WorkerStatus.SerializeToString,
                response_deserializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
                _registered_method=True)
        self.PostExecutorStatus = channel.unary_unary(
                '/RegistryService/PostExecutorStatus',
                request_serializer=crfs__router_dot_proto_dot_registry__pb2.ExecutorStatus.SerializeToString,
                response_deserializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
                _registered_method=True)
        self.PostWorkerUtilization = channel.unary_unary(
                '/RegistryService/PostWorkerUtilization',
                request_serializer=crfs__router_dot_proto_dot_registry__pb2.WorkerUtilization.SerializeToString,
                response_deserializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
                _registered_method=True)
        self.PostExecutorUtilization = channel.unary_unary(
                '/RegistryService/PostExecutorUtilization',
                request_serializer=crfs__router_dot_proto_dot_registry__pb2.ExecutorUtilization.SerializeToString,
                response_deserializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
                _registered_method=True)


class RegistryServiceServicer:
    """Service on the router to handle status and utilization updates from workers and executors
    """

    def PostWorkerStatus(self, request, context):
        """Unary RPC for posting worker status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostExecutorStatus(self, request, context):
        """Unary RPC for posting executor status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostWorkerUtilization(self, request, context):
        """Unary RPC for posting worker utilization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostExecutorUtilization(self, request, context):
        """Unary RPC for posting executor utilization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PostWorkerStatus,
                    request_deserializer=crfs__router_dot_proto_dot_registry__pb2.WorkerStatus.FromString,
                    response_serializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.SerializeToString,
            ),
            'PostExecutorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PostExecutorStatus,
                    request_deserializer=crfs__router_dot_proto_dot_registry__pb2.ExecutorStatus.FromString,
                    response_serializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.SerializeToString,
            ),
            'PostWorkerUtilization': grpc.unary_unary_rpc_method_handler(
                    servicer.PostWorkerUtilization,
                    request_deserializer=crfs__router_dot_proto_dot_registry__pb2.WorkerUtilization.FromString,
                    response_serializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.SerializeToString,
            ),
            'PostExecutorUtilization': grpc.unary_unary_rpc_method_handler(
                    servicer.PostExecutorUtilization,
                    request_deserializer=crfs__router_dot_proto_dot_registry__pb2.ExecutorUtilization.FromString,
                    response_serializer=crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistryService:
    """Service on the router to handle status and utilization updates from workers and executors
    """

    @staticmethod
    def PostWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegistryService/PostWorkerStatus',
            crfs__router_dot_proto_dot_registry__pb2.WorkerStatus.SerializeToString,
            crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostExecutorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegistryService/PostExecutorStatus',
            crfs__router_dot_proto_dot_registry__pb2.ExecutorStatus.SerializeToString,
            crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostWorkerUtilization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegistryService/PostWorkerUtilization',
            crfs__router_dot_proto_dot_registry__pb2.WorkerUtilization.SerializeToString,
            crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostExecutorUtilization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RegistryService/PostExecutorUtilization',
            crfs__router_dot_proto_dot_registry__pb2.ExecutorUtilization.SerializeToString,
            crfs__router_dot_proto_dot_registry__pb2.RegistryUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
