events {}

http {
    upstream grpc_router {
        server router:50051;
    }

    server {
        listen 50051 http2;

        location / {
            grpc_pass grpc://grpc_router;

            grpc_read_timeout 1h;
            grpc_send_timeout 1h;
        }
    }
}