events {}

http {
    upstream grpc_router {
        server router:50051;
    }

    server {
        listen 443 ssl;
        http2 on;
        
        # Public hostname of the router
        server_name readie.azurevm.io;

        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
            grpc_pass grpc://grpc_router;

            grpc_read_timeout 1h;
            grpc_send_timeout 1h;
        }
    }
}