// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: execution.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_RequestProvision_FullMethodName = "/ExecutionService/RequestProvision"
	ExecutionService_RequestExecution_FullMethodName = "/ExecutionService/RequestExecution"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service on the worker nodes to handle execution requests
type ExecutionServiceClient interface {
	// Unary RPC for requesting provisioning of a new executor or restarting an executor on worker
	RequestProvision(ctx context.Context, in *ExecutorProvisionRequest, opts ...grpc.CallOption) (*ExecutorProvisionResponse, error)
	// Bi-directional streaming RPC for streaming code execution input and output
	RequestExecution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerExecutionRequest, WorkerExecutionResponse], error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) RequestProvision(ctx context.Context, in *ExecutorProvisionRequest, opts ...grpc.CallOption) (*ExecutorProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutorProvisionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_RequestProvision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) RequestExecution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerExecutionRequest, WorkerExecutionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionService_ServiceDesc.Streams[0], ExecutionService_RequestExecution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerExecutionRequest, WorkerExecutionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_RequestExecutionClient = grpc.BidiStreamingClient[WorkerExecutionRequest, WorkerExecutionResponse]

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// Service on the worker nodes to handle execution requests
type ExecutionServiceServer interface {
	// Unary RPC for requesting provisioning of a new executor or restarting an executor on worker
	RequestProvision(context.Context, *ExecutorProvisionRequest) (*ExecutorProvisionResponse, error)
	// Bi-directional streaming RPC for streaming code execution input and output
	RequestExecution(grpc.BidiStreamingServer[WorkerExecutionRequest, WorkerExecutionResponse]) error
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) RequestProvision(context.Context, *ExecutorProvisionRequest) (*ExecutorProvisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestProvision not implemented")
}
func (UnimplementedExecutionServiceServer) RequestExecution(grpc.BidiStreamingServer[WorkerExecutionRequest, WorkerExecutionResponse]) error {
	return status.Error(codes.Unimplemented, "method RequestExecution not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_RequestProvision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutorProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).RequestProvision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_RequestProvision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).RequestProvision(ctx, req.(*ExecutorProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_RequestExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutionServiceServer).RequestExecution(&grpc.GenericServerStream[WorkerExecutionRequest, WorkerExecutionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_RequestExecutionServer = grpc.BidiStreamingServer[WorkerExecutionRequest, WorkerExecutionResponse]

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestProvision",
			Handler:    _ExecutionService_RequestProvision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestExecution",
			Handler:       _ExecutionService_RequestExecution_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "execution.proto",
}
