// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: execution.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message used for code execution requests to workers
type WorkerExecutionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId           string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkerId            string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Payload             []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ContainerId         *string                `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3,oneof" json:"container_id,omitempty"`
	CpuAlloc            *float64               `protobuf:"fixed64,6,opt,name=cpu_alloc,json=cpuAlloc,proto3,oneof" json:"cpu_alloc,omitempty"`
	GpuAlloc            *float64               `protobuf:"fixed64,7,opt,name=gpu_alloc,json=gpuAlloc,proto3,oneof" json:"gpu_alloc,omitempty"`
	CheckpointId        *string                `protobuf:"bytes,8,opt,name=checkpoint_id,json=checkpointId,proto3,oneof" json:"checkpoint_id,omitempty"`
	AdditionalResources []string               `protobuf:"bytes,9,rep,name=additional_resources,json=additionalResources,proto3" json:"additional_resources,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkerExecutionRequest) Reset() {
	*x = WorkerExecutionRequest{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerExecutionRequest) ProtoMessage() {}

func (x *WorkerExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerExecutionRequest.ProtoReflect.Descriptor instead.
func (*WorkerExecutionRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerExecutionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerExecutionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkerExecutionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerExecutionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerExecutionRequest) GetContainerId() string {
	if x != nil && x.ContainerId != nil {
		return *x.ContainerId
	}
	return ""
}

func (x *WorkerExecutionRequest) GetCpuAlloc() float64 {
	if x != nil && x.CpuAlloc != nil {
		return *x.CpuAlloc
	}
	return 0
}

func (x *WorkerExecutionRequest) GetGpuAlloc() float64 {
	if x != nil && x.GpuAlloc != nil {
		return *x.GpuAlloc
	}
	return 0
}

func (x *WorkerExecutionRequest) GetCheckpointId() string {
	if x != nil && x.CheckpointId != nil {
		return *x.CheckpointId
	}
	return ""
}

func (x *WorkerExecutionRequest) GetAdditionalResources() []string {
	if x != nil {
		return x.AdditionalResources
	}
	return nil
}

// Message used for code execution responses from workers
type WorkerExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Stdout        string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerExecutionResponse) Reset() {
	*x = WorkerExecutionResponse{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerExecutionResponse) ProtoMessage() {}

func (x *WorkerExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerExecutionResponse.ProtoReflect.Descriptor instead.
func (*WorkerExecutionResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerExecutionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerExecutionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkerExecutionResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerExecutionResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WorkerExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkerExecutionResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *WorkerExecutionResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\"\x95\x03\n" +
	"\x16WorkerExecutionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12&\n" +
	"\fcontainer_id\x18\x05 \x01(\tH\x00R\vcontainerId\x88\x01\x01\x12 \n" +
	"\tcpu_alloc\x18\x06 \x01(\x01H\x01R\bcpuAlloc\x88\x01\x01\x12 \n" +
	"\tgpu_alloc\x18\a \x01(\x01H\x02R\bgpuAlloc\x88\x01\x01\x12(\n" +
	"\rcheckpoint_id\x18\b \x01(\tH\x03R\fcheckpointId\x88\x01\x01\x121\n" +
	"\x14additional_resources\x18\t \x03(\tR\x13additionalResourcesB\x0f\n" +
	"\r_container_idB\f\n" +
	"\n" +
	"_cpu_allocB\f\n" +
	"\n" +
	"_gpu_allocB\x10\n" +
	"\x0e_checkpoint_id\"\xe1\x01\n" +
	"\x17WorkerExecutionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr2]\n" +
	"\x10ExecutionService\x12I\n" +
	"\x10RequestExecution\x12\x17.WorkerExecutionRequest\x1a\x18.WorkerExecutionResponse(\x010\x01BHZFgithub.com/illinoisdata/checkpoint-restore-for-serverless/worker/protob\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_execution_proto_goTypes = []any{
	(*WorkerExecutionRequest)(nil),  // 0: WorkerExecutionRequest
	(*WorkerExecutionResponse)(nil), // 1: WorkerExecutionResponse
}
var file_execution_proto_depIdxs = []int32{
	0, // 0: ExecutionService.RequestExecution:input_type -> WorkerExecutionRequest
	1, // 1: ExecutionService.RequestExecution:output_type -> WorkerExecutionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	file_execution_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
