// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_PostWorkerStatus_FullMethodName        = "/RegistryService/PostWorkerStatus"
	RegistryService_PostExecutorStatus_FullMethodName      = "/RegistryService/PostExecutorStatus"
	RegistryService_PostWorkerUtilization_FullMethodName   = "/RegistryService/PostWorkerUtilization"
	RegistryService_PostExecutorUtilization_FullMethodName = "/RegistryService/PostExecutorUtilization"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service on the router to handle status and utilization updates from workers and executors
type RegistryServiceClient interface {
	// Unary RPC for posting worker status
	PostWorkerStatus(ctx context.Context, in *WorkerStatus, opts ...grpc.CallOption) (*RegistryUpdateResponse, error)
	// Unary RPC for posting executor status
	PostExecutorStatus(ctx context.Context, in *ExecutorStatus, opts ...grpc.CallOption) (*RegistryUpdateResponse, error)
	// Unary RPC for posting worker utilization
	PostWorkerUtilization(ctx context.Context, in *WorkerUtilization, opts ...grpc.CallOption) (*RegistryUpdateResponse, error)
	// Unary RPC for posting executor utilization
	PostExecutorUtilization(ctx context.Context, in *ExecutorUtilization, opts ...grpc.CallOption) (*RegistryUpdateResponse, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) PostWorkerStatus(ctx context.Context, in *WorkerStatus, opts ...grpc.CallOption) (*RegistryUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpdateResponse)
	err := c.cc.Invoke(ctx, RegistryService_PostWorkerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) PostExecutorStatus(ctx context.Context, in *ExecutorStatus, opts ...grpc.CallOption) (*RegistryUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpdateResponse)
	err := c.cc.Invoke(ctx, RegistryService_PostExecutorStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) PostWorkerUtilization(ctx context.Context, in *WorkerUtilization, opts ...grpc.CallOption) (*RegistryUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpdateResponse)
	err := c.cc.Invoke(ctx, RegistryService_PostWorkerUtilization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) PostExecutorUtilization(ctx context.Context, in *ExecutorUtilization, opts ...grpc.CallOption) (*RegistryUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryUpdateResponse)
	err := c.cc.Invoke(ctx, RegistryService_PostExecutorUtilization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
//
// Service on the router to handle status and utilization updates from workers and executors
type RegistryServiceServer interface {
	// Unary RPC for posting worker status
	PostWorkerStatus(context.Context, *WorkerStatus) (*RegistryUpdateResponse, error)
	// Unary RPC for posting executor status
	PostExecutorStatus(context.Context, *ExecutorStatus) (*RegistryUpdateResponse, error)
	// Unary RPC for posting worker utilization
	PostWorkerUtilization(context.Context, *WorkerUtilization) (*RegistryUpdateResponse, error)
	// Unary RPC for posting executor utilization
	PostExecutorUtilization(context.Context, *ExecutorUtilization) (*RegistryUpdateResponse, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) PostWorkerStatus(context.Context, *WorkerStatus) (*RegistryUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostWorkerStatus not implemented")
}
func (UnimplementedRegistryServiceServer) PostExecutorStatus(context.Context, *ExecutorStatus) (*RegistryUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostExecutorStatus not implemented")
}
func (UnimplementedRegistryServiceServer) PostWorkerUtilization(context.Context, *WorkerUtilization) (*RegistryUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostWorkerUtilization not implemented")
}
func (UnimplementedRegistryServiceServer) PostExecutorUtilization(context.Context, *ExecutorUtilization) (*RegistryUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostExecutorUtilization not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_PostWorkerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).PostWorkerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_PostWorkerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).PostWorkerStatus(ctx, req.(*WorkerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_PostExecutorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutorStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).PostExecutorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_PostExecutorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).PostExecutorStatus(ctx, req.(*ExecutorStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_PostWorkerUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerUtilization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).PostWorkerUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_PostWorkerUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).PostWorkerUtilization(ctx, req.(*WorkerUtilization))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_PostExecutorUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutorUtilization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).PostExecutorUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_PostExecutorUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).PostExecutorUtilization(ctx, req.(*ExecutorUtilization))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostWorkerStatus",
			Handler:    _RegistryService_PostWorkerStatus_Handler,
		},
		{
			MethodName: "PostExecutorStatus",
			Handler:    _RegistryService_PostExecutorStatus_Handler,
		},
		{
			MethodName: "PostWorkerUtilization",
			Handler:    _RegistryService_PostWorkerUtilization_Handler,
		},
		{
			MethodName: "PostExecutorUtilization",
			Handler:    _RegistryService_PostExecutorUtilization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
