// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resources.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A resource whose budget a caller can set per function. Kept deliberately
// generic: a new dimension is one enum value here, one capacity source in the
// router, and (where the runtime can enforce it) one grower in the worker.
type ResourceKind int32

const (
	ResourceKind_RESOURCE_KIND_UNKNOWN    ResourceKind = 0
	ResourceKind_RESOURCE_KIND_MEMORY     ResourceKind = 1 // system RAM, in bytes
	ResourceKind_RESOURCE_KIND_GPU_MEMORY ResourceKind = 2 // GPU device memory, in bytes
)

// Enum value maps for ResourceKind.
var (
	ResourceKind_name = map[int32]string{
		0: "RESOURCE_KIND_UNKNOWN",
		1: "RESOURCE_KIND_MEMORY",
		2: "RESOURCE_KIND_GPU_MEMORY",
	}
	ResourceKind_value = map[string]int32{
		"RESOURCE_KIND_UNKNOWN":    0,
		"RESOURCE_KIND_MEMORY":     1,
		"RESOURCE_KIND_GPU_MEMORY": 2,
	}
)

func (x ResourceKind) Enum() *ResourceKind {
	p := new(ResourceKind)
	*p = x
	return p
}

func (x ResourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_proto_enumTypes[0].Descriptor()
}

func (ResourceKind) Type() protoreflect.EnumType {
	return &file_resources_proto_enumTypes[0]
}

func (x ResourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceKind.Descriptor instead.
func (ResourceKind) EnumDescriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{0}
}

// A single resource budget: what to start with and how far it may grow.
//
// Both are byte counts. `alloc` is the initial reservation the router places on
// and the worker sets at container create; `0` means "unset, apply the default".
// `max` is the auto-expand ceiling; `0` means "bounded only by worker capacity".
type ResourceBudget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ResourceKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=ResourceKind" json:"kind,omitempty"`
	Alloc         int64                  `protobuf:"varint,2,opt,name=alloc,proto3" json:"alloc,omitempty"`
	Max           int64                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceBudget) Reset() {
	*x = ResourceBudget{}
	mi := &file_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceBudget) ProtoMessage() {}

func (x *ResourceBudget) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceBudget.ProtoReflect.Descriptor instead.
func (*ResourceBudget) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceBudget) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNKNOWN
}

func (x *ResourceBudget) GetAlloc() int64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *ResourceBudget) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_resources_proto protoreflect.FileDescriptor

const file_resources_proto_rawDesc = "" +
	"\n" +
	"\x0fresources.proto\"[\n" +
	"\x0eResourceBudget\x12!\n" +
	"\x04kind\x18\x01 \x01(\x0e2\r.ResourceKindR\x04kind\x12\x14\n" +
	"\x05alloc\x18\x02 \x01(\x03R\x05alloc\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x03R\x03max*a\n" +
	"\fResourceKind\x12\x19\n" +
	"\x15RESOURCE_KIND_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14RESOURCE_KIND_MEMORY\x10\x01\x12\x1c\n" +
	"\x18RESOURCE_KIND_GPU_MEMORY\x10\x02BHZFgithub.com/illinoisdata/checkpoint-restore-for-serverless/worker/protob\x06proto3"

var (
	file_resources_proto_rawDescOnce sync.Once
	file_resources_proto_rawDescData []byte
)

func file_resources_proto_rawDescGZIP() []byte {
	file_resources_proto_rawDescOnce.Do(func() {
		file_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_proto_rawDesc), len(file_resources_proto_rawDesc)))
	})
	return file_resources_proto_rawDescData
}

var file_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resources_proto_goTypes = []any{
	(ResourceKind)(0),      // 0: ResourceKind
	(*ResourceBudget)(nil), // 1: ResourceBudget
}
var file_resources_proto_depIdxs = []int32{
	0, // 0: ResourceBudget.kind:type_name -> ResourceKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resources_proto_init() }
func file_resources_proto_init() {
	if File_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_proto_rawDesc), len(file_resources_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_proto_goTypes,
		DependencyIndexes: file_resources_proto_depIdxs,
		EnumInfos:         file_resources_proto_enumTypes,
		MessageInfos:      file_resources_proto_msgTypes,
	}.Build()
	File_resources_proto = out.File
	file_resources_proto_goTypes = nil
	file_resources_proto_depIdxs = nil
}
