// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: router.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterService_RequestExecution_FullMethodName = "/RouterService/RequestExecution"
	RouterService_AssignExecution_FullMethodName  = "/RouterService/AssignExecution"
)

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterServiceClient interface {
	RequestExecution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientExecutionRequest, ClientExecutionResponse], error)
	AssignExecution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerExecutionRequest, WorkerExecutionResponse], error)
}

type routerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterServiceClient(cc grpc.ClientConnInterface) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) RequestExecution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientExecutionRequest, ClientExecutionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouterService_ServiceDesc.Streams[0], RouterService_RequestExecution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientExecutionRequest, ClientExecutionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouterService_RequestExecutionClient = grpc.BidiStreamingClient[ClientExecutionRequest, ClientExecutionResponse]

func (c *routerServiceClient) AssignExecution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerExecutionRequest, WorkerExecutionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouterService_ServiceDesc.Streams[1], RouterService_AssignExecution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerExecutionRequest, WorkerExecutionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouterService_AssignExecutionClient = grpc.BidiStreamingClient[WorkerExecutionRequest, WorkerExecutionResponse]

// RouterServiceServer is the server API for RouterService service.
// All implementations must embed UnimplementedRouterServiceServer
// for forward compatibility.
type RouterServiceServer interface {
	RequestExecution(grpc.BidiStreamingServer[ClientExecutionRequest, ClientExecutionResponse]) error
	AssignExecution(grpc.BidiStreamingServer[WorkerExecutionRequest, WorkerExecutionResponse]) error
	mustEmbedUnimplementedRouterServiceServer()
}

// UnimplementedRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServiceServer struct{}

func (UnimplementedRouterServiceServer) RequestExecution(grpc.BidiStreamingServer[ClientExecutionRequest, ClientExecutionResponse]) error {
	return status.Error(codes.Unimplemented, "method RequestExecution not implemented")
}
func (UnimplementedRouterServiceServer) AssignExecution(grpc.BidiStreamingServer[WorkerExecutionRequest, WorkerExecutionResponse]) error {
	return status.Error(codes.Unimplemented, "method AssignExecution not implemented")
}
func (UnimplementedRouterServiceServer) mustEmbedUnimplementedRouterServiceServer() {}
func (UnimplementedRouterServiceServer) testEmbeddedByValue()                       {}

// UnsafeRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServiceServer will
// result in compilation errors.
type UnsafeRouterServiceServer interface {
	mustEmbedUnimplementedRouterServiceServer()
}

func RegisterRouterServiceServer(s grpc.ServiceRegistrar, srv RouterServiceServer) {
	// If the following call panics, it indicates UnimplementedRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterService_ServiceDesc, srv)
}

func _RouterService_RequestExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouterServiceServer).RequestExecution(&grpc.GenericServerStream[ClientExecutionRequest, ClientExecutionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouterService_RequestExecutionServer = grpc.BidiStreamingServer[ClientExecutionRequest, ClientExecutionResponse]

func _RouterService_AssignExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouterServiceServer).AssignExecution(&grpc.GenericServerStream[WorkerExecutionRequest, WorkerExecutionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouterService_AssignExecutionServer = grpc.BidiStreamingServer[WorkerExecutionRequest, WorkerExecutionResponse]

// RouterService_ServiceDesc is the grpc.ServiceDesc for RouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestExecution",
			Handler:       _RouterService_RequestExecution_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AssignExecution",
			Handler:       _RouterService_AssignExecution_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "router.proto",
}
