"""Regenerate the cross-language framing fixture.

    uv run python tests/generate_golden.py

The Go tests in worker/internal/executor read this file and decode it with their
own implementation. Two hand-written implementations of one wire format drift;
a shared fixture is what makes the drift a test failure instead of a production
incident months later.

Deliberately hand-rolled here rather than produced by calling write_message: a
fixture generated by the code under test cannot catch that code changing.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

CASES: list[tuple[str, list[bytes]]] = [
    ("empty", []),
    ("single_chunk", [b"hello"]),
    ("two_chunks", [b"hello ", b"world"]),
    ("many_chunks", [bytes([i]) * 7 for i in range(16)]),
    # Version 1 could not carry these bytes at all: they were the terminator.
    ("old_terminator_bytes", [b"EOF"]),
    ("ends_with_terminator_bytes", [b"payload-EOF"]),
    ("only_terminator_bytes", [b"EOFEOFEOF"]),
    # Every byte value, so an implementation that mangles non-ASCII fails here.
    ("all_byte_values", [bytes(range(256))]),
    ("nul_bytes", [b"\x00\x00\x00", b"\x00"]),
    ("large_chunk", [b"x" * 70000]),
]


def encode(chunks: list[bytes]) -> bytes:
    """Frame chunks the way the protocol says, without using the protocol code."""
    out = bytearray()
    for chunk in chunks:
        out += struct.pack(">Q", len(chunk))
        out += chunk
    out += struct.pack(">Q", 0)  # terminator
    return bytes(out)


def main() -> None:
    """Write the fixture as JSON with hex-encoded bytes."""
    fixture = {
        "protocol_version": 2,
        "note": "Generated by executor/tests/generate_golden.py. Read by both suites.",
        "cases": [
            {
                "name": name,
                "payload_hex": b"".join(chunks).hex(),
                "encoded_hex": encode(chunks).hex(),
            }
            for name, chunks in CASES
        ],
    }

    path = Path(__file__).parent / "data" / "frames.golden.json"
    path.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {len(CASES)} cases to {path}")


if __name__ == "__main__":
    main()
