import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per top-level section, so each navbar tab shows only its own pages.
// Pages inside a section are ordered by `sidebar_position` in their front matter.
const sidebars: SidebarsConfig = {
  gettingStarted: [{type: 'autogenerated', dirName: 'getting-started'}],
  concepts: [{type: 'autogenerated', dirName: 'concepts'}],
  architecture: [{type: 'autogenerated', dirName: 'architecture'}],
  guides: [{type: 'autogenerated', dirName: 'guides'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
  contributing: [{type: 'autogenerated', dirName: 'contributing'}],
};

export default sidebars;
